# Generated by Django 5.0 on 2024-04-03 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_wishlistitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitems',
            old_name='cars',
            new_name='car',
        ),
        migrations.RemoveField(
            model_name='wishlistitems',
            name='items',
        ),
        migrations.AddField(
            model_name='wishlistitems',
            name='wishlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='accounts.cart'),
            preserve_default=False,
        ),
    ]
