# Generated by Django 5.0 on 2024-04-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_wishlistitems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitems',
            name='user',
        ),
    ]
