# Generated by Django 5.0 on 2024-04-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
