# Generated by Django 5.0 on 2024-04-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_total_amount_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_amount_spent',
        ),
    ]
