# Generated by Django 5.0 on 2024-04-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_location_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razor_pay_payment_signature',
        ),
    ]
