# Generated by Django 5.0 on 2024-04-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_cart_amount'),
        ('cars', '0009_alter_coupon_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car'),
        ),
    ]
