# Generated by Django 5.0 on 2024-04-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
