# Generated by Django 5.0 on 2024-04-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearbox',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
