# Generated by Django 5.0 on 2024-04-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_gearbox_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default=1, upload_to='car'),
            preserve_default=False,
        ),
    ]
