# Generated by Django 5.0 on 2024-04-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
